google_sheets:
  creds_path: "./secrets/google-service-account.json"
  aux_sheet_id: "1Zli1oqL-_I1usmRAkOZtRTXdTWeHF6E-OTKKhgJwKPE"
  ranges:
    desembolsos:
      address: "DESEMBOLSOS!A1:AV5000"
      extract:
        customer_name_field: "Cliente"
        customer_id_field: "Customer ID"
        kam_field: "KAM"
        credit_line_field: "LineaCredito"
    cliente_data:
      address: "Data!A1:Z20000"
      extract:
        customer_id_field: "Customer ID"
        credit_line_field: "LineaCredito"

