# Days Past Due (DPD) Policy Configuration
# Defines DPD thresholds and bucketing rules for Abaco loan analysis

# Default DPD Threshold for loan classification
default_threshold:
  days: 180 # Loans beyond 180 days are considered defaults
  description: "Standard commercial lending threshold"

# Delinquency Bucket Definitions
# Maps days past due to risk categories
delinquency_buckets:
  current:
    days_range: [0, 0]
    description: "No payment delays"
    risk_level: "low"

  early_delinquent:
    days_range: [1, 30]
    description: "1-30 days past due"
    risk_level: "low"

  moderate_delinquent:
    days_range: [31, 60]
    description: "31-60 days past due"
    risk_level: "medium"

  late_delinquent:
    days_range: [61, 90]
    description: "61-90 days past due"
    risk_level: "medium-high"

  severe_delinquent:
    days_range: [91, 120]
    description: "91-120 days past due"
    risk_level: "high"

  default:
    days_range: [121, 180]
    description: "121-180 days past due"
    risk_level: "very-high"

  npl:
    days_range: [181, 999]
    description: "Non-performing loan (>180 days)"
    risk_level: "critical"

# Risk Weight Mappings for calculations
risk_weights:
  current: 0.0
  early_delinquent: 0.1
  moderate_delinquent: 0.3
  late_delinquent: 0.5
  severe_delinquent: 0.7
  default: 0.9
  npl: 1.0

# Provisioning Requirements by bucket
provisioning_rates:
  current: 0.01 # 1% provision
  early_delinquent: 0.02 # 2% provision
  moderate_delinquent: 0.05 # 5% provision
  late_delinquent: 0.15 # 15% provision
  severe_delinquent: 0.30 # 30% provision
  default: 0.50 # 50% provision
  npl: 1.00 # 100% provision

# Abaco-specific settings
abaco_settings:
  factoring_threshold: 180 # Days for factoring products
  bullet_payment_grace: 5 # Grace period for bullet payments
  currency: "USD"
  companies:
    - "Abaco Technologies"
    - "Abaco Financial"

# Reporting Configuration
reporting:
  include_grace_period: true
  round_days: true
  export_bucket_details: true

# Performance Monitoring
monitoring:
  alert_thresholds:
    high_risk_percentage: 0.15 # Alert if >15% of portfolio is high risk
    npl_percentage: 0.05 # Alert if >5% of portfolio is NPL
    avg_dpd_threshold: 30 # Alert if average DPD >30 days
