# Column Mapping Configuration
# Maps dataset field names to contract field names
# Update these mappings if your field names differ from the contracts

# Loan/Portfolio Dataset Column Mappings
loan_data:
  company: "Company"
  customer_id: "Customer ID"
  customer_name: "Cliente"
  payer_name: "Pagador"
  loan_id: "Loan ID"
  application_id: "Application ID"
  product_type: "Product Type"
  loan_currency: "Loan Currency"
  loan_amount: "Disbursement Amount"
  outstanding_balance: "Outstanding Loan Value"
  interest_rate: "Interest Rate APR"
  origination_date: "Disbursement Date"
  term_days: "Term"
  term_unit: "Term Unit"
  payment_frequency: "Payment Frequency"
  days_past_due: "Days in Default"
  loan_status: "Loan Status"
  past_due_amount: "past_due_amount"
  first_arrears_date: "first_arrears_date"
  last_payment_date: "last_payment_date"
  last_due_date: "last_due_date"
  reference_date: "reference_date"

# Payment Dataset Column Mappings
payment_data:
  loan_id: "Loan ID"
  payment_date: "Payment Date"
  total_payment: "Total Payment"
  principal_paid: "Principal Payment"
  interest_paid: "Interest Payment"
  fees_paid: "Fee Payment"
  tax_paid: "Tax Payment"
  outstanding_balance: "Outstanding Loan Value"
  currency: "Currency"
  tpv: "TPV"

# DPD Frame Output Columns (Contract Output)
dpd_frame_output:
  past_due_amount: "past_due_amount"
  days_past_due: "days_past_due"
  first_arrears_date: "first_arrears_date"
  last_payment_date: "last_payment_date"
  last_due_date: "last_due_date"
  is_default: "is_default"
  reference_date: "reference_date"

# Buckets Output Columns (Contract Output)
buckets_output:
  dpd_bucket: "dpd_bucket"
  dpd_bucket_value: "dpd_bucket_value"
  dpd_bucket_description: "dpd_bucket_description"
  default_flag: "default_flag"

# Customer/Entity Dataset Column Mappings
customer_data:
  business_year_founded: "Business Year Founded"
  equifax_score: "Equifax Score"
  category: "Category"
  credit_line_category: "Credit Line Category"
  subcategory: "Subcategory"
  credit_line_subcategory: "Credit Line Subcategory"
  industry: "Industry"
  birth_year: "Birth Year"
  occupation: "Occupation"
  client_type: "Client Type"
  location_city: "Location City"
  location_state_province: "Location State/Province"
  location_country: "Location Country"
  customer_id: "Customer ID"
  customer_name: "Customer Name"
  kam_assigned: "KAM"
  credit_line: "Credit Line"

# Collateral Dataset Column Mappings
collateral_data:
  customer_id: "Customer ID"
  customer_name: "Customer Name"
  loan_id: "Loan ID"
  collateral_id: "Collateral ID"
  collateral_original_value: "Collateral Original"
  collateral_current_value: "Collateral Current"
