# Column Mapping Configuration
# Maps dataset field names to contract field names
# Update these mappings if your field names differ from the contracts

# Loan/Portfolio Dataset Column Mappings
loan_data:
<<<<<<< HEAD
  # Core Loan Identifiers
  loan_id: "loan_id"              # Unique loan identifier
  customer_id: "customer_id"      # Customer identifier
  
  # Loan Details
  loan_amount: "amount"           # Original loan amount
  outstanding_balance: "balance"  # Current outstanding balance
  interest_rate: "rate"           # Interest rate
  
  # Dates
  origination_date: "origination_date"
  maturity_date: "maturity_date"
  last_payment_date: "last_payment_date"
  last_due_date: "last_due_date"
  first_arrears_date: "first_arrears_date"
  reference_date: "reference_date"
  
  # Status Fields
  loan_status: "status"
  days_past_due: "dpd"
  past_due_amount: "past_due_amount"
  
  # Tenor Information
  tenor_months: "tenor_months"
  tenor_days: "tenor_days"

# Payment Dataset Column Mappings
payment_data:
  payment_id: "payment_id"
  loan_id: "loan_id"
  payment_date: "payment_date"
  payment_amount: "payment_amount"
  principal_paid: "principal_paid"
  interest_paid: "interest_paid"
  fees_paid: "fees_paid"
=======
  company: "Company"
  customer_id: "Customer ID"
  customer_name: "Cliente"
  payer_name: "Pagador"
  loan_id: "Loan ID"
  application_id: "Application ID"
  product_type: "Product Type"
  loan_currency: "Loan Currency"
  loan_amount: "Disbursement Amount"
  outstanding_balance: "Outstanding Loan Value"
  interest_rate: "Interest Rate APR"
  origination_date: "Disbursement Date"
  term_days: "Term"
  term_unit: "Term Unit"
  payment_frequency: "Payment Frequency"
  days_past_due: "Days in Default"
  loan_status: "Loan Status"
  past_due_amount: "past_due_amount"
  first_arrears_date: "first_arrears_date"
  last_payment_date: "last_payment_date"
  last_due_date: "last_due_date"
  reference_date: "reference_date"

# Payment Dataset Column Mappings
payment_data:
  loan_id: "Loan ID"
  payment_date: "Payment Date"
  total_payment: "Total Payment"
  principal_paid: "Principal Payment"
  interest_paid: "Interest Payment"
  fees_paid: "Fee Payment"
  tax_paid: "Tax Payment"
  outstanding_balance: "Outstanding Loan Value"
  currency: "Currency"
  tpv: "TPV"
>>>>>>> fa393d2be80b675bbc0b12c922c156c6c1d27af7

# DPD Frame Output Columns (Contract Output)
dpd_frame_output:
  past_due_amount: "past_due_amount"
  days_past_due: "days_past_due"
  first_arrears_date: "first_arrears_date"
  last_payment_date: "last_payment_date"
  last_due_date: "last_due_date"
  is_default: "is_default"
  reference_date: "reference_date"

# Buckets Output Columns (Contract Output)
buckets_output:
  dpd_bucket: "dpd_bucket"
  dpd_bucket_value: "dpd_bucket_value"
  dpd_bucket_description: "dpd_bucket_description"
  default_flag: "default_flag"

# Customer/Entity Dataset Column Mappings
customer_data:
<<<<<<< HEAD
  customer_id: "customer_id"
  customer_name: "customer_name"
  customer_type: "customer_type"
  registration_date: "registration_date"
  credit_score: "credit_score"
=======
  customer_id: "Customer ID"
  customer_name: "Customer Name"
  business_year_founded: "Business Year Founded"
  business_legal_name: "Business Legal Name"
  tax_id: "Tax ID"
  duns_number: "DUNS Number"
  equifax_score: "Equifax Score"
  experian_score: "Experian Score"
  transunion_score: "TransUnion Score"
  internal_risk_rating: "Internal Risk Rating"
  category: "Category"
  credit_line_category: "Credit Line Category"
  subcategory: "Subcategory"
  credit_line_subcategory: "Credit Line Subcategory"
  industry: "Industry"
  industry_code: "Industry Code"
  naics_code: "NAICS Code"
  sic_code: "SIC Code"
  birth_year: "Birth Year"
  occupation: "Occupation"
  client_type: "Client Type"
  business_type: "Business Type"
  annual_revenue: "Annual Revenue"
  employee_count: "Employee Count"
  years_in_business: "Years in Business"
  debt_to_income_ratio: "Debt to Income Ratio"
  location_city: "Location City"
  location_state_province: "Location State/Province"
  location_country: "Location Country"
  location_postal_code: "Postal Code"
  primary_address: "Primary Address"
  kam_assigned: "KAM"
  relationship_manager: "Relationship Manager"
  onboarding_date: "Onboarding Date"
  last_review_date: "Last Review Date"
  next_review_date: "Next Review Date"
  credit_line: "LineaCredito"
  approved_limit: "Approved Limit"
  available_limit: "Available Limit"
  utilization_rate: "Utilization Rate"
  customer_segment: "Customer Segment"
  risk_tier: "Risk Tier"
  pricing_tier: "Pricing Tier"
  kyc_status: "KYC Status"
  aml_status: "AML Status"
  regulatory_status: "Regulatory Status"

# Collateral Dataset Column Mappings
collateral_data:
  customer_id: "Customer ID"
  customer_name: "Cliente"
  loan_id: "Loan ID"
  collateral_id: "Collateral ID"
  collateral_type: "Collateral Type"
  collateral_category: "Collateral Category"
  collateral_description: "Collateral Description"
  collateral_original_value: "Garantía Original"
  collateral_current_value: "Garantía Actual"
  collateral_appraised_value: "Appraised Value"
  collateral_liquidation_value: "Liquidation Value"
  appraisal_date: "Appraisal Date"
  next_appraisal_date: "Next Appraisal Date"
  appraiser_name: "Appraiser Name"
  collateral_location: "Collateral Location"
  collateral_condition: "Collateral Condition"
  lien_position: "Lien Position"
  insurance_provider: "Insurance Provider"
  insurance_policy_number: "Insurance Policy Number"
  insurance_coverage_amount: "Insurance Coverage Amount"
  insurance_expiry_date: "Insurance Expiry Date"
  loan_to_value_ratio: "Loan to Value Ratio"
  advance_rate: "Advance Rate"
  haircut_percentage: "Haircut Percentage"
  valuation_method: "Valuation Method"
  monitoring_frequency: "Monitoring Frequency"
  last_monitoring_date: "Last Monitoring Date"
  collateral_status: "Collateral Status"
  perfection_status: "Perfection Status"
  ucc_filing_number: "UCC Filing Number"
  ucc_filing_date: "UCC Filing Date"
  ucc_expiry_date: "UCC Expiry Date"

# Financial Statement Dataset Column Mappings
financial_data:
  customer_id: "Customer ID"
  statement_date: "Statement Date"
  statement_type: "Statement Type"
  fiscal_year_end: "Fiscal Year End"
  total_assets: "Total Assets"
  current_assets: "Current Assets"
  cash_equivalents: "Cash and Equivalents"
  accounts_receivable: "Accounts Receivable"
  inventory: "Inventory"
  fixed_assets: "Fixed Assets"
  total_liabilities: "Total Liabilities"
  current_liabilities: "Current Liabilities"
  long_term_debt: "Long Term Debt"
  total_equity: "Total Equity"
  revenue: "Revenue"
  gross_profit: "Gross Profit"
  operating_income: "Operating Income"
  net_income: "Net Income"
  ebitda: "EBITDA"
  debt_service_coverage: "Debt Service Coverage"
  current_ratio: "Current Ratio"
  quick_ratio: "Quick Ratio"
  debt_to_equity: "Debt to Equity"
  return_on_assets: "Return on Assets"
  return_on_equity: "Return on Equity"
  working_capital: "Working Capital"

# Portfolio Analysis Output Mappings
portfolio_analysis:
  total_exposure: "total_exposure"
  weighted_average_rate: "weighted_average_rate"
  average_maturity: "average_maturity"
  concentration_ratio: "concentration_ratio"
  diversification_index: "diversification_index"
  risk_adjusted_return: "risk_adjusted_return"
  expected_loss: "expected_loss"
  unexpected_loss: "unexpected_loss"
  economic_capital: "economic_capital"
  raroc: "raroc"
  portfolio_beta: "portfolio_beta"
  correlation_matrix: "correlation_matrix"

# Regulatory Reporting Mappings
regulatory_data:
  call_report_code: "Call Report Code"
  risk_weight: "Risk Weight"
  regulatory_capital: "Regulatory Capital"
  tier1_capital: "Tier 1 Capital"
  tier2_capital: "Tier 2 Capital"
  rwc_ratio: "Risk Weighted Capital Ratio"
  leverage_ratio: "Leverage Ratio"
  liquidity_ratio: "Liquidity Ratio"
  provision_rate: "Provision Rate"
  charge_off_rate: "Charge Off Rate"
  recovery_rate: "Recovery Rate"
  stressed_loss_rate: "Stressed Loss Rate"
>>>>>>> fa393d2be80b675bbc0b12c922c156c6c1d27af7
