# Pricing Configuration
# Defines pricing grids and interval bands

# Band key definitions for interval matching
band_keys:
  tenor_days:
    lower_bound: "tenor_min"
    upper_bound: "tenor_max"
  amount:
    lower_bound: "amount_min"
    upper_bound: "amount_max"

# Pricing file paths
pricing_files:
  main_pricing: "data/pricing/main_pricing.csv"
  commercial_loans: "data/pricing/commercial_loans_pricing.csv"
  retail_loans: "data/pricing/retail_loans_pricing.csv"
  risk_based: "data/pricing/risk_based_pricing.csv"

# Default pricing parameters
defaults:
  base_rate: 0.05
  margin: 0.02
  currency: "USD"

# Abaco-specific pricing settings
abaco_pricing:
  factoring_rate_range: [0.15, 0.40] # 15% to 40% APR
  advance_rate_max: 0.95 # Maximum 95% of TPV
  term_days_range: [30, 180] # 30 to 180 days

# Export settings
export_settings:
  include_calculations: true
  round_decimals: 4
