# Column mapping configuration for Commercial-View
loan_columns:
  customer_id: "customer_id"
  loan_id: "loan_id"
  loan_amount: "loan_amount"
  apr: "apr"
  term: "term"
  disbursement_date: "disbursement_date"

payment_columns:
  payment_id: "payment_id"
  loan_id: "loan_id"
  payment_date: "payment_date"
  payment_amount: "payment_amount"
  days_past_due: "days_past_due"
