# Export configuration for Commercial-View
export_paths:
  base_path: "./abaco_runtime/exports"
  kpi_json: "./abaco_runtime/exports/kpi/json"
  kpi_csv: "./abaco_runtime/exports/kpi/csv"
  dpd: "./abaco_runtime/exports/dpd"
  buckets: "./abaco_runtime/exports/buckets"

google_drive:
  folder_id: "1qIg_BnIf_IWYcWqCuvLaYU_Gu4C2-Dj8"
  enabled: true
