# Commercial-View Pricing Configuration
# Production-ready configuration for commercial lending analytics

# Core Pricing Parameters
base_rates:
  prime_rate: 7.50
  base_spread: 2.00
  risk_adjustment: 1.25

# Risk Categories - Fixed duplicate key issue
risk_categories:
  low_risk:
    multiplier: 0.85
    max_ltv: 80.0
    min_dscr: 1.25
  medium_risk:
    multiplier: 1.00
    max_ltv: 75.0
    min_dscr: 1.35
  high_risk:
    multiplier: 1.25
    max_ltv: 65.0
    min_dscr: 1.50

# Loan Types - Fixed duplicate key issue
loan_types:
  term_loan:
    base_rate: 8.50
    fees: 1.5
  credit_line:
    base_rate: 9.25
    fees: 2.0
  equipment_finance:
    base_rate: 7.75
    fees: 1.75

# Market Conditions
market_adjustments:
  current_environment: "stable"
  volatility_factor: 0.15
  regulatory_buffer: 0.25

# Compliance Requirements
compliance_requirements:
  regulatory_capital_ratio: 12.0
  stress_test_multiplier: 1.15
  documentation_score_minimum: 85.0
