name: CI SSH Checkout Test

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ssh-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH for deploy key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_VISUAL_CI_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Test SSH clone
        shell: bash
        run: |
          git clone git@github.com:${{ github.repository }}.git repo
          cd repo
          git fetch --all --tags --prune
          git rev-parse --short HEAD

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.9-${{ hashFiles('repo/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.9-

      - name: Install dependencies
        shell: bash
        run: |
          cd repo
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Import smoke test
        shell: bash
        run: |
          cd repo
          if grep -i '^flask' requirements.txt >/dev/null 2>&1; then \
            python -c "import flask; print('✅ Flask import works')"; \
          else \
            echo "⚠️ Flask not in requirements.txt, skipping import test."; \
          fi
          if grep -i '^sklearn' requirements.txt >/dev/null 2>&1; then \
            python -c "import sklearn; print('✅ Sklearn import works')"; \
          else \
            echo "⚠️ Sklearn not in requirements.txt, skipping import test."; \
          fi

      - name: Run unit tests (verbose)
        shell: bash
        run: |
          cd repo
          if [ -d tests ]; then python -m unittest discover tests/ -v; else echo "No tests/ directory found, skipping unit tests."; fi
