name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend Python validation
    runs-on: ubuntu-latest
    env:
      LOOKER_BASE_URL: ${{ secrets.LOOKER_BASE_URL }}
      LOOKER_CLIENT_ID: ${{ secrets.LOOKER_CLIENT_ID }}
      LOOKER_CLIENT_SECRET: ${{ secrets.LOOKER_CLIENT_SECRET }}
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      CI: true
    steps:
      - name: Configure SSH access (optional)
        if: secrets.CI_DEPLOY_SSH_KEY != ''
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CI_DEPLOY_SSH_KEY }}

      - name: Add GitHub to known hosts
        if: secrets.CI_DEPLOY_SSH_KEY != ''
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Set up virtual environment and install dependencies
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Pylint (errors only)
        shell: bash
        run: |
          source .venv/bin/activate
          PYTHONPATH=src pylint --disable=all --enable=E src/looker_client.py src/models.py src/figma_client.py

      - name: Mypy type checking
        shell: bash
        run: |
          source .venv/bin/activate
          mypy --config-file mypy.ini

      - name: Run unit tests
        shell: bash
        run: |
          source .venv/bin/activate
          pytest tests/test_figma_client.py -q

      - name: Backend build (bytecode compilation)
        shell: bash
        run: |
          source .venv/bin/activate
          python -m compileall src

  frontend:
    name: Frontend TypeScript validation
    runs-on: ubuntu-latest
    needs: backend
    env:
      CI: true
    defaults:
      run:
        working-directory: frontend/dashboard
    steps:
      - name: Configure SSH access (optional)
        if: secrets.CI_DEPLOY_SSH_KEY != ''
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CI_DEPLOY_SSH_KEY }}

      - name: Add GitHub to known hosts
        if: secrets.CI_DEPLOY_SSH_KEY != ''
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/dashboard/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint frontend
        run: npm run lint

      - name: Type check frontend
        run: npm run type-check

      - name: Run frontend unit tests
        run: npm test -- --watchAll=false

      - name: Build frontend
        run: npm run build
