name: Daily refresh

on:
  schedule:
    - cron: "0 6 * * *"   # Daily at 06:00 UTC
  workflow_dispatch:      # Manual execution allowed

permissions:
  contents: write
  actions: read

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt || true

      - name: Clean target directory (remove manual uploads)
        run: |
          safe_dir="data"
          test "$safe_dir" != "" && test "$safe_dir" != "/" || (echo "Invalid safe_dir"; exit 1)
          git rm -r --cached "$safe_dir" >/dev/null 2>&1 || true
          rm -rf "${safe_dir:?}/"*  # Delete everything inside data/

      - name: Rebuild/load fresh data
        run: |
          python scripts/refresh_data.py  # Daily data loading logic

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "Daily refresh: clean & reload data"
          git push
